### ISSUE TITLE
TuxCoin Wallet won"t synchronize with database :(

### ISSUE THREAD

**Issue by JustFragger** [bleach86/tuxcoin-V2#10]
**Hello !** 
Recently I created my tuxcoin wallet,but when it starts it says I"m 1 year and 35 week behind and it won"t synchronize at all I waited some time but nothing 
Attaching screenshot below ..
![Screenshot_1](https://user-images.githubusercontent.com/16962301/74943356-a6930500-53f4-11ea-922c-478710e644f0.png)

In advance thanks for any useful answers
_Best Regards_ 
**-Mathew**

**Comment by JustFragger** [comment]
Okay So I fixed this with tux config file edited it by adding specific values from #help discord server

**Comment by pacobartek** [comment]
hello and what u do,my wallet no respond at all

**Comment by pacobartek** [comment]
and i think we have very simular issue

**Comment by bleach86** [comment]
> and i think we have very simular issue

you can add peers from here
https://explore.tuxtoke.life/network

**Comment by pacobartek** [comment]
thank you ,thats helps thx a lot
